<?php
/* mPDF UTF-8 capability test - development only, do not deploy to production */

require_once __DIR__ . '/vendor/autoload.php';

$barcodeGenerator = new Picqer\Barcode\BarcodeGeneratorSVG();

$mpdf = new \Mpdf\Mpdf([
    'mode'           => 'utf-8',
    'format'         => 'A4',
    'margin_top'     => 10,
    'margin_bottom'  => 10,
    'margin_left'    => 10,
    'margin_right'   => 10,
    'autoScriptToLang' => true,
    'autoLangToFont'   => true,
]);

// font-family values map to bundled TTF filenames (lowercase, no extension):
//   freeserif   → FreeSerif.ttf  (Hebrew, Arabic, Greek, Cyrillic, Latin)
//   sun-exta    → Sun-ExtA.ttf   (CJK)
$labels = [
    [
        'script'  => 'Latin (German)',
        'lang'    => 'de',
        'font'    => 'freeserif',
        'dir'     => 'ltr',
        'title'   => 'Über die Entstehung der Arten',
        'author'  => 'Charles Darwin',
        'barcode' => 'DE000001',
    ],
    [
        'script'  => 'Cyrillic (Russian)',
        'lang'    => 'ru',
        'font'    => 'freeserif',
        'dir'     => 'ltr',
        'title'   => 'Война и мир',
        'author'  => 'Лев Толстой',
        'barcode' => 'RU000002',
    ],
    [
        'script'  => 'Hebrew (RTL)',
        'lang'    => 'he',
        'font'    => 'freeserif',
        'dir'     => 'rtl',
        'title'   => 'מלחמה ושלום',
        'author'  => 'לב טולסטוי',
        'barcode' => 'HE000003',
    ],
    [
        'script'  => 'Arabic (RTL)',
        'lang'    => 'ar',
        'font'    => 'freeserif',
        'dir'     => 'rtl',
        'title'   => 'ألف ليلة وليلة',
        'author'  => 'مجهول',
        'barcode' => 'AR000004',
    ],
    [
        'script'  => 'Chinese (CJK)',
        'lang'    => 'zh',
        'font'    => 'sun-exta',
        'dir'     => 'ltr',
        'title'   => '西游记',
        'author'  => '吴承恩',
        'barcode' => 'ZH000005',
    ],
    [
        'script'  => 'Greek',
        'lang'    => 'el',
        'font'    => 'freeserif',
        'dir'     => 'ltr',
        'title'   => 'Ὀδύσσεια',
        'author'  => 'Ὅμηρος',
        'barcode' => 'GR000006',
    ],
];

$cells = '';
foreach ($labels as $label) {
    $textStyle = 'font-family: ' . $label['font'] . '; direction: ' . $label['dir'] . ';';
    $cells .= '
    <td style="width:88mm; height:38mm; border:0.5pt solid #aaa; padding:3mm; vertical-align:middle;">
        <p style="font-size:7pt; color:#888; margin:0 0 1mm 0;">' . htmlspecialchars($label['script']) . '</p>
        <p lang="' . $label['lang'] . '" style="font-size:10pt; font-weight:bold; margin:0 0 1mm 0; ' . $textStyle . '">'
            . htmlspecialchars($label['title']) . '</p>
        <p lang="' . $label['lang'] . '" style="font-size:8pt; margin:0 0 2mm 0; ' . $textStyle . '">'
            . htmlspecialchars($label['author']) . '</p>
        <img style="width:60mm; height:10mm;" src="data:image/svg+xml;base64,
            ' . base64_encode($barcodeGenerator->getBarcode($label['barcode'], $barcodeGenerator::TYPE_CODE_128)) . '" />
        <p style="font-size:7pt; text-align:center; margin:0;">' . htmlspecialchars($label['barcode']) . '</p>
    </td>';
}

$html = '
<h2 style="font-size:12pt; margin-bottom:4mm;">mPDF UTF-8 Label Test</h2>
<table style="border-collapse:collapse; width:100%;">
    <tr>' . $cells . '</tr>
</table>
<p style="font-size:8pt; color:#888; margin-top:6mm;">
    Generated by mPDF ' . \Mpdf\Mpdf::VERSION . ' &mdash; tests Latin, Cyrillic, Hebrew (RTL), Arabic (RTL), CJK, and Greek scripts.
</p>';

$mpdf->WriteHTML($html);
$mpdf->Output('mpdf_utf8_test.pdf', 'I');
